name: Python Script and Snyk Scan with Email Notification

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  security-and-script:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run Snyk to check for vulnerabilities
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
        continue-on-error: true  # Continue even if vulnerabilities are found


      # Step 6: Run the Python script
      - name: Run Python script
        run: python script.py

      # Step 7: Send email notification
      - name: Send email notification
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: smtp-relay.brevo.com
          smtp-port: 587
          smtp-secure: true
          username: ${{ secrets.EM_USERNAME }}
          password: ${{ secrets.EM_PASSWORD }}
          subject: Snyk Scan and Python Script Execution Report
          from-email: wisdomkingsley75@gmail.com
          to-email: joshwoods9115@gmail.com
          html: |
            <h1> This is a test demo </h1>
            <p> Yo </p.>
